-- Phase 10 요금제 (BandPlan, 결제 어댑터 제외)
--
-- band_plans  밴드별 요금제. band_id 전역 유니크 — 밴드당 정확히 한 행이고, 티어 변경은
--             새 행을 만들지 않고 이 행을 제자리 수정한다(started_at·expires_at 갱신).
--             생성 시점(BandService.create)에 FREE 로 한 행 만든다.
--
--             tier=FREE  → media_retention_days = 30, expires_at = NULL.
--             tier=PREMIUM→ media_retention_days = NULL(무제한), expires_at = 현재 구독기간 종료.
--             ck_band_plans_retention 이 이 불변식을 DB 레벨에서 강제한다.
--
--             expires_at 는 이번 릴리스에서 "정보성"이다 — 저장·응답에 노출만 하고, 경과 시
--             자동으로 FREE 로 되돌리는 배치는 실제 PG 연동 Phase 로 미룬다(no-op 게이트웨이는
--             구독을 만료시키지 않는다).
--
--             subscription_ref 는 결제 게이트웨이가 돌려주는 불투명 구독 식별자다. no-op 은
--             "noop-{bandId}" 를 쓴다. 실제 어댑터(향후)의 renew/cancel 이 이 값을 참조한다.
--
--             media_attachments.expires_at 재계산: 업그레이드 시 밴드의 READY 미디어를 NULL 로,
--             다운그레이드 시 now + 유예기간(기본 30일)으로 덮어쓴다(plan/board 서비스가 처리).

CREATE TABLE band_plans (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    band_id              BIGINT       NOT NULL REFERENCES bands(id),
    tier                 VARCHAR(20)  NOT NULL DEFAULT 'FREE',
    media_retention_days INTEGER,
    subscription_ref     VARCHAR(100),
    started_at           TIMESTAMPTZ  NOT NULL,
    expires_at           TIMESTAMPTZ,
    created_at           TIMESTAMPTZ  NOT NULL,
    updated_at           TIMESTAMPTZ  NOT NULL,

    CONSTRAINT ux_band_plans_band UNIQUE (band_id),
    CONSTRAINT ck_band_plans_tier CHECK (tier IN ('FREE', 'PREMIUM')),
    -- FREE 는 보관일수가 있어야 하고, PREMIUM 은 NULL(무제한)이어야 한다.
    CONSTRAINT ck_band_plans_retention CHECK (
        (tier = 'FREE'    AND media_retention_days IS NOT NULL AND media_retention_days > 0)
     OR (tier = 'PREMIUM' AND media_retention_days IS NULL)
    ),
    -- FREE 인 밴드는 구독기간 종료일이 없다.
    CONSTRAINT ck_band_plans_free_no_expiry CHECK (tier = 'PREMIUM' OR expires_at IS NULL)
);

-- 기존 밴드 전부에 FREE 행을 채운다. Phase 10 코드는 밴드마다 요금제 행이 있다고 가정한다
-- (ddl-auto: validate). '30' 은 BandPlan.FREE_RETENTION_DAYS 와 일치시킨다(SQL 은 Java 상수를
-- 참조할 수 없어 리터럴로 둔다). ux_band_plans_band 로 재실행해도 중복이 생기지 않는다.
INSERT INTO band_plans (band_id, tier, media_retention_days, started_at, created_at, updated_at)
SELECT b.id, 'FREE', 30, b.created_at, now(), now()
FROM bands b;

COMMENT ON COLUMN band_plans.tier IS 'FREE 또는 PREMIUM. 밴드장만 변경할 수 있다.';
COMMENT ON COLUMN band_plans.media_retention_days IS
    '첨부 미디어 보관일수. FREE=30, PREMIUM=NULL(무제한).';
COMMENT ON COLUMN band_plans.subscription_ref IS
    '결제 게이트웨이의 불투명 구독 식별자. no-op 구현체는 "noop-{bandId}".';
COMMENT ON COLUMN band_plans.expires_at IS
    'PREMIUM 현재 구독기간 종료 시각. 이번 릴리스에서는 정보성 — 경과해도 자동 다운그레이드하지 않는다.';
