-- 요금제 맛보기 쿠폰
--
-- plan_coupons              운영자가 발급하는 PREMIUM 맛보기 쿠폰. 30/60/90일 등 기간을 부여한다.
--                           구조는 band_invites(V2)와 같은 문제(코드·사용횟수·기한·무효화)라 같은 모양이다.
--                           코드는 InviteCodeGenerator 의 8자 알파벳(혼동 문자 제외)을 재사용한다.
--
--                           발급은 앱에 화면이 없다 — 이 서비스에는 앱 전역 관리자 역할이 없어서
--                           (밴드 내 LEADER/MEMBER 뿐) 관리자 인증 체계를 새로 만드는 대신
--                           운영자가 직접 INSERT 한다. 앱은 사용(redeem)만 한다. 예시:
--
--                             INSERT INTO plan_coupons (code, grant_days, max_uses, expires_at, created_at)
--                             VALUES ('BANDULE7', 30, 100, now() + interval '90 days', now());
--
-- plan_coupon_redemptions   어느 밴드가 어느 쿠폰을 썼는지. (coupon_id, band_id) 유니크로 같은 밴드의
--                           반복 사용을 DB 레벨에서 막는다 — 애플리케이션은 이 제약 위반을
--                           COUPON_ALREADY_USED 로 변환한다.

CREATE TABLE plan_coupons (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(8)  NOT NULL,
    grant_days  INT         NOT NULL,
    max_uses    INT,
    used_count  INT         NOT NULL DEFAULT 0,
    expires_at  TIMESTAMPTZ,
    revoked     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL,

    CONSTRAINT ux_plan_coupons_code UNIQUE (code),
    CONSTRAINT ck_plan_coupons_days CHECK (grant_days > 0),
    CONSTRAINT ck_plan_coupons_uses CHECK (used_count >= 0 AND (max_uses IS NULL OR max_uses > 0))
);

COMMENT ON COLUMN plan_coupons.grant_days IS 'PREMIUM 을 며칠 부여할지. 이미 PREMIUM 이면 남은 기간에 더한다.';
COMMENT ON COLUMN plan_coupons.max_uses   IS 'NULL 이면 사용 횟수 무제한.';
COMMENT ON COLUMN plan_coupons.expires_at IS '쿠폰 자체를 쓸 수 있는 기한. NULL 이면 무기한.';

CREATE TABLE plan_coupon_redemptions (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id   BIGINT      NOT NULL REFERENCES plan_coupons(id),
    band_id     BIGINT      NOT NULL REFERENCES bands(id),
    redeemed_by BIGINT      NOT NULL REFERENCES users(id),
    redeemed_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT ux_plan_coupon_redemptions UNIQUE (coupon_id, band_id)
);
