-- 약관 동의 기록
--
-- terms_agreements   회원이 언제 어느 버전의 약관·개인정보처리방침에 동의했는지.
--
--                    그동안 동의는 앱 화면에서 체크만 받고 **아무 데도 남지 않았다.** 나중에
--                    "동의한 적 없다" 는 다툼이 생기면 입증할 근거가 없다. 개인정보 수집·이용
--                    동의는 받았다는 사실 자체를 보관해야 의미가 있다.
--
--                    한 회원에게 여러 행이 쌓인다. 약관이 바뀌면 새 버전으로 다시 받아야 하고,
--                    그때 이력이 필요하다. (user_id, terms_version, privacy_version) 유니크로
--                    같은 버전을 두 번 기록하지 않는다 - 재로그인 때마다 행이 늘면 이력이 아니라
--                    잡음이 된다.
--
--                    버전 문자열은 문서의 시행일(예: '2026-09-06')이다. 서버 설정
--                    app.terms.version / app.terms.privacy-version 에서 온다.
--
--                    회원이 탈퇴해도 이 행은 남긴다. 개인정보를 담고 있지 않고(어느 계정이
--                    언제 동의했는지 뿐), 동의 이력은 탈퇴 후에도 보존해야 의미가 있다.
--                    users 행이 익명화되어도 user_id 는 유지된다.

CREATE TABLE terms_agreements (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT      NOT NULL REFERENCES users(id),
    terms_version    VARCHAR(20) NOT NULL,
    privacy_version  VARCHAR(20) NOT NULL,
    agreed_at        TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX ux_terms_agreements_user_version
    ON terms_agreements (user_id, terms_version, privacy_version);

CREATE INDEX ix_terms_agreements_user ON terms_agreements (user_id);
