-- Phase 1 인증 — 사용자 계정
--
-- 신원 기준은 (social_provider, social_id). 이메일은 이메일 가입자(social_provider IS NULL)에게만
-- 자격증명이다. 카카오 행의 email 은 프로필 데이터일 뿐이라, 같은 이메일의 이메일계정과 카카오계정이
-- 공존할 수 있다(계정 연동은 Phase 1 범위 밖).
--
-- 탈퇴는 deleted_at 기록(소프트 삭제)이고, 90일 뒤 배치가 개인정보 컬럼을 NULL 로 만든다(익명화).
-- 익명화된 행도 남겨 이후 Phase 의 FK 무결성(게시글·정산의 작성자)을 유지한다.

CREATE TABLE users (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255),
    password_hash   VARCHAR(100),
    name            VARCHAR(50)  NOT NULL,
    social_provider VARCHAR(20),
    social_id       VARCHAR(64),
    created_at      TIMESTAMPTZ  NOT NULL,
    deleted_at      TIMESTAMPTZ,

    CONSTRAINT ck_users_social_provider
        CHECK (social_provider IS NULL OR social_provider IN ('KAKAO')),

    -- 가입 수단별 필수 값. 익명화로 값이 NULL 이 되는 탈퇴 행은 검사에서 제외한다.
    CONSTRAINT ck_users_credential CHECK (
        deleted_at IS NOT NULL
        OR (social_provider IS NULL
            AND email IS NOT NULL AND password_hash IS NOT NULL AND social_id IS NULL)
        OR (social_provider IS NOT NULL
            AND social_id IS NOT NULL AND password_hash IS NULL)
    )
);

-- 이메일 유일성은 "활성 이메일 계정" 안에서만 강제한다.
-- social_provider IS NULL 조건이 없으면, 이미 이메일 가입한 주소로 카카오 로그인 시 INSERT 가 터진다.
CREATE UNIQUE INDEX ux_users_email_active
    ON users (email)
    WHERE deleted_at IS NULL AND social_provider IS NULL;

-- 소셜 신원 유일성. 익명화된 행(social_id NULL)과 탈퇴 행은 제외.
CREATE UNIQUE INDEX ux_users_social_active
    ON users (social_provider, social_id)
    WHERE deleted_at IS NULL AND social_id IS NOT NULL;

-- 90일 파기 배치 조회용.
CREATE INDEX ix_users_deleted_at
    ON users (deleted_at)
    WHERE deleted_at IS NOT NULL;

COMMENT ON COLUMN users.email IS '카카오가 이메일 동의를 주지 않으면 NULL. 익명화 시 NULL.';
COMMENT ON COLUMN users.password_hash IS 'DelegatingPasswordEncoder 해시({bcrypt} 접두). 이메일 가입자만 값이 있다.';
COMMENT ON COLUMN users.social_provider IS 'NULL = 이메일 가입. 그 외 KAKAO.';
COMMENT ON COLUMN users.deleted_at IS '소프트 삭제 시각. 이 값 + 90일 후 개인정보 컬럼을 파기한다.';
