-- Phase 2 밴드 · 초대 · 멤버
--
-- bands            밴드. leader_id 는 "현재 밴드장"의 캐시이며, 진실은 band_members 의 활성 LEADER 행이다.
-- band_members     밴드 참여 이력. 탈퇴/추방은 left_at 기록(소프트). 재가입은 새 행.
-- band_invites     초대코드. 재발급 시 기존 코드를 revoked 처리하므로 밴드당 활성 코드는 보통 0~1개다.
--
-- 시간대 겹침 차단 등 "예약 시스템"스러운 제약은 이 서비스의 범위가 아니다(BUILD_PLAN 2장).

CREATE TABLE bands (
    id                     BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   VARCHAR(50) NOT NULL,
    leader_id              BIGINT      NOT NULL REFERENCES users(id),
    reservation_permission VARCHAR(20) NOT NULL DEFAULT 'LEADER_ONLY',
    created_at             TIMESTAMPTZ NOT NULL,

    CONSTRAINT ck_bands_reservation_permission
        CHECK (reservation_permission IN ('LEADER_ONLY', 'ANYONE', 'APPROVAL_REQUIRED'))
);

COMMENT ON COLUMN bands.leader_id IS '현재 밴드장 user_id. band_members 의 활성 LEADER 행과 항상 일치한다(위임 시 함께 갱신).';
COMMENT ON COLUMN bands.reservation_permission IS '일정 등록 권한. 기본 LEADER_ONLY. 밴드장이 설정에서 변경.';


CREATE TABLE band_members (
    id        BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    band_id   BIGINT      NOT NULL REFERENCES bands(id),
    user_id   BIGINT      NOT NULL REFERENCES users(id),
    role      VARCHAR(20) NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL,
    left_at   TIMESTAMPTZ,

    CONSTRAINT ck_band_members_role CHECK (role IN ('LEADER', 'MEMBER'))
);

-- 한 사용자는 한 밴드에 활성 멤버십을 하나만 가진다. 탈퇴(left_at 기록) 후 재가입은 새 행이라 충돌하지 않는다.
CREATE UNIQUE INDEX ux_band_members_active
    ON band_members (band_id, user_id)
    WHERE left_at IS NULL;

-- 밴드당 활성 LEADER 는 정확히 한 명. 위임은 "기존 LEADER 강등 → flush → 대상 승격" 순서라 이 인덱스에 걸리지 않는다.
CREATE UNIQUE INDEX ux_band_members_single_leader
    ON band_members (band_id)
    WHERE left_at IS NULL AND role = 'LEADER';

-- "내가 속한 밴드 목록" 조회용.
CREATE INDEX ix_band_members_user_active
    ON band_members (user_id)
    WHERE left_at IS NULL;

COMMENT ON COLUMN band_members.left_at IS '자발적 탈퇴 또는 밴드장 추방 시각. NULL 이면 활성 멤버.';


CREATE TABLE band_invites (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    band_id     BIGINT      NOT NULL REFERENCES bands(id),
    code        VARCHAR(8)  NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    max_uses    INT,
    used_count  INT         NOT NULL DEFAULT 0,
    revoked     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_by  BIGINT      NOT NULL REFERENCES users(id),
    created_at  TIMESTAMPTZ NOT NULL
);

-- code 는 전역 유일(8자, 혼동 문자 0/O/1/I 제외 영숫자). 참여 시 이 값만으로 밴드를 찾는다.
CREATE UNIQUE INDEX ux_band_invites_code ON band_invites (code);
CREATE INDEX ix_band_invites_band ON band_invites (band_id, created_at DESC);

COMMENT ON COLUMN band_invites.max_uses IS 'NULL 이면 사용 횟수 무제한. 값이 있으면 used_count 가 그 값에 도달할 때 소진.';
COMMENT ON COLUMN band_invites.created_at IS 'Phase 2에서 도메인 모델에 추가 승인된 컬럼. 활성 코드 최신순 조회·감사에 쓴다.';
