-- Phase 3 합주실 (Room)
--
-- rooms  밴드가 등록해 둔 합주 장소. 밴드별로 독립 등록한다 — 여러 밴드가 같은 물리적 합주실을
--        각자 등록해도 별개 레코드다(BUILD_PLAN 3장, DESIGN 4.2).
--
-- 이 테이블은 "예약 가능한 자원"이 아니라 주소록에 가깝다. 가용시간·예약 상태를 갖지 않는다.
-- lat/lng 는 네이버 지오코딩 결과이며 NULL 을 허용한다 — 지오코딩이 실패해도 주소만으로 등록되어야
-- 한다는 것이 Phase 3 완료 기준이다.

CREATE TABLE rooms (
    id          BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    band_id     BIGINT           NOT NULL REFERENCES bands(id),
    name        VARCHAR(50)      NOT NULL,
    address     VARCHAR(255),
    lat         DOUBLE PRECISION,
    lng         DOUBLE PRECISION,
    phone       VARCHAR(30),
    memo        VARCHAR(500),
    usage_count INT              NOT NULL DEFAULT 0,
    created_by  BIGINT           NOT NULL REFERENCES users(id),
    created_at  TIMESTAMPTZ      NOT NULL,
    deleted_at  TIMESTAMPTZ
);

-- 목록 조회 전용: 밴드별 usage_count 내림차순(Phase 3 완료 기준의 정렬).
CREATE INDEX ix_rooms_band_usage
    ON rooms (band_id, usage_count DESC)
    WHERE deleted_at IS NULL;

-- 한 밴드 안에서 합주실 이름은 유일하다. 삭제된 행은 제외하므로 지웠던 이름을 다시 쓸 수 있다.
CREATE UNIQUE INDEX ux_rooms_band_name_active
    ON rooms (band_id, name)
    WHERE deleted_at IS NULL;

COMMENT ON COLUMN rooms.address IS '사용자가 입력한 주소 원문. NULL 허용 — 이름만 있는 장소(멤버 집 등)도 등록 가능.';
COMMENT ON COLUMN rooms.lat IS '네이버 지오코딩 결과 위도(WGS84). 지오코딩 미설정·실패 시 NULL.';
COMMENT ON COLUMN rooms.lng IS '네이버 지오코딩 결과 경도(WGS84). 지오코딩 미설정·실패 시 NULL.';
COMMENT ON COLUMN rooms.usage_count IS '이 합주실로 등록된 일정 수. Phase 4 일정 등록에서 증가시킨다. 목록 정렬 기준.';
COMMENT ON COLUMN rooms.deleted_at IS 'Phase 3에서 도메인 모델에 추가 승인된 컬럼. 소프트 삭제 — 삭제 후에도 과거 일정이 합주실 정보를 참조할 수 있어야 한다.';
