-- Phase 4 일정 등록 (Reservation)
--
-- reservations  밴드가 "이미 외부에서 잡아 둔 합주 예약"을 앱에 기록한 것. 이 서비스는 예약을 대행하지
--               않으므로 이 행은 합주실의 실제 예약 상태가 아니라 "밴드 내부 일정으로서의 등록 상태"다
--               (BUILD_PLAN 3장, 도메인 모델 Reservation 주석).
--
-- status 는 밴드 설정(bands.reservation_permission)에 따라 등록 직후 값이 갈린다:
--   LEADER_ONLY / ANYONE  -> CONFIRMED (즉시 확정)
--   APPROVAL_REQUIRED      -> PENDING  (밴드장 승인 시 CONFIRMED, 거절 시 REJECTED)
-- 취소는 CANCELLED. 행은 남는다(과거 기록·정산 참조).
--
-- 겹침 차단은 이 서비스의 범위가 아니다(BUILD_PLAN 2장 2번). 시간대가 겹치는 일정도 그대로 저장되어야
-- 하므로 EXCLUDE 제약(tstzrange &&)이나 유니크 제약을 "일부러 두지 않는다". 겹침은 애플리케이션이
-- 응답에 경고로만 싣고 등록을 거부하지 않는다.

CREATE TABLE reservations (
    id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    band_id           BIGINT      NOT NULL REFERENCES bands(id),
    room_id           BIGINT      NOT NULL REFERENCES rooms(id),
    requested_by      BIGINT      NOT NULL REFERENCES users(id),
    status            VARCHAR(20) NOT NULL,
    start_at          TIMESTAMPTZ NOT NULL,
    end_at            TIMESTAMPTZ NOT NULL,
    cost              INT,
    note              VARCHAR(500),
    recurring_rule_id BIGINT,
    created_at        TIMESTAMPTZ NOT NULL,

    CONSTRAINT ck_reservations_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'REJECTED')),
    -- 시간 순서만 강제한다. 서로 다른 일정끼리의 겹침은 막지 않는다.
    CONSTRAINT ck_reservations_period CHECK (end_at > start_at)
);

-- 캘린더 조회: 밴드별 기간(start_at, end_at) 범위 겹침 검색.
CREATE INDEX ix_reservations_band_period ON reservations (band_id, start_at, end_at);
-- 합주실 삭제/사용 집계 시 역참조.
CREATE INDEX ix_reservations_room ON reservations (room_id);

COMMENT ON COLUMN reservations.status IS
    '밴드 내부 일정으로서의 등록 상태(실제 합주실 예약 상태가 아니다). PENDING/CONFIRMED/CANCELLED/REJECTED.';
COMMENT ON COLUMN reservations.room_id IS
    'rooms 는 소프트 삭제이므로 삭제된 합주실을 참조하는 과거 일정도 계속 유효하다.';
COMMENT ON COLUMN reservations.cost IS '합주실 비용(원). 정산(Phase 7)의 입력이 아니라 참고용 메모 성격. NULL 허용.';
COMMENT ON COLUMN reservations.note IS '외부 예약 방법 자유 기재 (예: "카톡 예약 완료, 예약자 홍길동").';
COMMENT ON COLUMN reservations.recurring_rule_id IS
    'Phase 5 정기 일정에서 채운다. Phase 4 에서는 항상 NULL 이며 recurring_rules 테이블·FK 는 Phase 5 마이그레이션에서 추가한다.';
