-- Phase 5 정기 일정 (RecurringRule)
--
-- recurring_rules  "매주 토요일 15:00~18:00 합주" 같은 반복 규칙. 규칙을 등록하면 앞으로의 회차가
--                  reservations 행으로 미리 만들어진다(Phase 4 의 일정과 같은 테이블·같은 상태 흐름).
--                  규칙 자체는 합주실의 실제 예약이 아니라 "밴드 내부 일정 생성 틀"이다.
--
-- day_of_week / start_time / end_time 은 로컬(Asia/Seoul) 기준이다. 회차의 start_at·end_at(UTC)은
-- app.recurring.zone 으로 변환해 계산한다. 서울은 DST 가 없어 모호 시각이 생기지 않는다.
--
-- frequency 별 회차 산출:
--   WEEKLY   start_date 이후 처음 맞는 요일 + 7일 간격
--   BIWEEKLY 같은 anchor + 14일 간격
--   MONTHLY  anchor 가 "그 달의 몇 번째 요일"인지 유도해 매월 같은 주차·요일
--            (예: 매월 둘째 주 토요일). 그 주차가 없는 달(5번째 토요일 등)은 건너뛴다.
--
-- created_at / deleted_at 은 BUILD_PLAN 3장 필드 목록에 없으나 지시자 승인을 받아 추가했다:
--   created_at  다른 모든 테이블과 동일(BaseTimeEntity). 규칙 목록 최신순 정렬·감사용.
--   deleted_at  소프트 삭제 필수. 규칙을 하드 삭제하면 과거 회차의 recurring_rule_id FK 가 깨져
--               "규칙 삭제 후에도 과거 일정이 남는다"(Phase 5 완료 기준)를 만족할 수 없다.
--               rooms.deleted_at 과 같은 선례. 규칙 삭제는 deleted_at 을 찍고, 미래 회차만 CANCELLED 로 바꾼다.
--   cost / note 회차 전체에 동일하게 복사되는 값. 배치가 이어 만드는 회차도 같은 값을 갖도록 규칙에 저장한다.

CREATE TABLE recurring_rules (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    band_id     BIGINT      NOT NULL REFERENCES bands(id),
    room_id     BIGINT      NOT NULL REFERENCES rooms(id),
    frequency   VARCHAR(20) NOT NULL,
    day_of_week VARCHAR(10) NOT NULL,   -- java.time.DayOfWeek 이름 (MONDAY … SUNDAY)
    start_time  TIME        NOT NULL,   -- 로컬(Asia/Seoul) 시각
    end_time    TIME        NOT NULL,
    start_date  DATE        NOT NULL,
    end_date    DATE,                   -- NULL = 종료일 없음(배치가 계속 이어 만든다)
    cost        INT,                    -- 회차 전체에 복사. 참고용 메모 성격(정산 입력 아님)
    note        VARCHAR(500),           -- 회차 전체에 복사
    created_by  BIGINT      NOT NULL REFERENCES users(id),
    created_at  TIMESTAMPTZ NOT NULL,
    deleted_at  TIMESTAMPTZ,            -- 소프트 삭제. 과거 회차가 계속 참조한다.

    CONSTRAINT ck_recurring_rules_frequency CHECK (frequency IN ('WEEKLY', 'BIWEEKLY', 'MONTHLY')),
    CONSTRAINT ck_recurring_rules_time   CHECK (end_time > start_time),
    CONSTRAINT ck_recurring_rules_period CHECK (end_date IS NULL OR end_date >= start_date)
);

-- 활성 규칙 목록(밴드별, 최신순). 배치도 활성 규칙만 훑는다.
CREATE INDEX ix_recurring_rules_band ON recurring_rules (band_id, created_at DESC)
    WHERE deleted_at IS NULL;

-- Phase 4 가 컬럼만 뚫어 둔 reservations.recurring_rule_id 에 이제 FK 를 건다.
ALTER TABLE reservations
    ADD CONSTRAINT fk_reservations_recurring_rule
    FOREIGN KEY (recurring_rule_id) REFERENCES recurring_rules(id);

-- 규칙별 회차 조회(상세·마지막 회차·미래 회차 취소) + "같은 규칙 + 같은 start_at" 중복 방지를 한 인덱스로.
-- 이 UNIQUE 는 "겹침 차단"이 아니다 — 서로 다른 규칙·수동 등록 일정끼리의 시간대 겹침은 여전히 전혀 막지
-- 않는다(BUILD_PLAN 2장 2번). 오직 한 규칙이 같은 시작 시각의 회차를 두 번 만드는 것만 막는다
-- (배치 재실행·동시 실행 멱등성). 개별 회차를 취소해도 행은 남으므로 배치가 다시 돌아도 취소한 회차가
-- 되살아나지 않는다. (recurring_rule_id, start_at) prefix 조회·정렬도 이 인덱스로 처리된다.
CREATE UNIQUE INDEX ux_reservations_rule_slot ON reservations (recurring_rule_id, start_at)
    WHERE recurring_rule_id IS NOT NULL;

COMMENT ON COLUMN recurring_rules.day_of_week IS
    'java.time.DayOfWeek 이름. start_time/end_time 과 함께 로컬(Asia/Seoul) 기준으로 회차 시각을 만든다.';
COMMENT ON COLUMN recurring_rules.deleted_at IS
    '소프트 삭제. 규칙 삭제 시 이 값을 찍고 미래 회차만 CANCELLED 로 바꾼다. 과거 회차는 그대로 둔다.';
COMMENT ON COLUMN recurring_rules.cost IS '생성되는 모든 회차에 복사되는 비용(원). 참고용, 정산 입력 아님. NULL 허용.';
