-- Phase 6 참석 체크(RSVP) · 셋리스트
--
-- reservation_attendances  일정별 멤버 참석 응답. 일정이 만들어질 때 "그 시점의" 활성 밴드 멤버 전원에
--                          대해 PENDING 행을 미리 만든다(BUILD_PLAN Phase 6). 일정 생성 이후 밴드에
--                          합류한 멤버는 응답 시점에 행이 없으므로, 참석 상태 변경 API 가 행을 만들어
--                          upsert 한다(완료 기준: 나중에 합류한 멤버도 응답 가능). 일정 상세의 집계
--                          "참석 N / 전체 M" 은 저장된 행이 아니라 "현재" 활성 멤버 기준으로 계산한다.
--                          (reservation_id, user_id) 유니크 — 한 멤버가 한 일정에 응답 하나.
--
-- setlist_items  일정별 연주 곡 목록. order_no(1부터) 로 정렬하며 서버가 부여한다. 재정렬 API 가
--                1..N 을 다시 매긴다. 곡 중복 등은 막지 않는다(자유 기재). reference_url 은 참고 링크.

CREATE TABLE reservation_attendances (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT      NOT NULL REFERENCES reservations(id),
    user_id        BIGINT      NOT NULL REFERENCES users(id),
    status         VARCHAR(20) NOT NULL,
    responded_at   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL,

    CONSTRAINT ck_reservation_attendances_status
        CHECK (status IN ('ATTENDING', 'ABSENT', 'PENDING')),
    CONSTRAINT ux_reservation_attendances_member UNIQUE (reservation_id, user_id)
);

-- 일정 상세의 참석 현황(일정별 전체 행 조회).
CREATE INDEX ix_reservation_attendances_reservation ON reservation_attendances (reservation_id);

CREATE TABLE setlist_items (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT        NOT NULL REFERENCES reservations(id),
    title          VARCHAR(200)  NOT NULL,
    artist         VARCHAR(200),
    reference_url  VARCHAR(2000),
    order_no       INT           NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL,

    CONSTRAINT ck_setlist_items_order_no CHECK (order_no > 0)
);

-- 일정별 셋리스트를 순서대로 조회.
CREATE INDEX ix_setlist_items_reservation ON setlist_items (reservation_id, order_no);

COMMENT ON COLUMN reservation_attendances.status IS
    '멤버의 참석 응답. 일정 생성 시 PENDING 으로 시작하고 본인이 ATTENDING/ABSENT 로 바꾼다.';
COMMENT ON COLUMN reservation_attendances.responded_at IS
    '본인이 ATTENDING/ABSENT 로 응답한 시각. PENDING(미응답)이면 NULL.';
COMMENT ON COLUMN setlist_items.order_no IS
    '연주 순서(1부터). 서버가 부여하며 재정렬 API 로 1..N 을 다시 매긴다.';
