-- Phase 7 정산(N빵)
--
-- settlements  일정 하나에 매긴 "방값 총액"과 그것을 어떻게 나눌지(split_type). 일정당 하나만 존재한다
--              (ux_settlements_reservation). 총액을 다시 입력하거나 참석자가 바뀌면 재계산 API 로 갱신하며,
--              서버가 참석 응답 변화를 감지해 자동으로 다시 나누지는 않는다(BUILD_PLAN Phase 7).
--
--   split_type = EQUAL           현재 활성 밴드 멤버 전원 균등분배
--              = ATTENDEES_ONLY  참석(reservation_attendances.status = 'ATTENDING')인 멤버만 균등분배
--                                참석자가 0명이면 정산을 만들지 않는다(애플리케이션에서 409).
--
-- settlement_shares  멤버 한 명이 낼 몫. 나누어떨어지지 않는 나머지는 "밴드장 먼저 → 가입일 순"으로
--                    앞에서부터 1원씩 더해, 합계가 항상 total_amount 와 일치한다. paid 는 본인이 직접
--                    체크하는 셀프 리포트다(다른 멤버가 대신 바꿀 수 없다). 재계산 시 남는 멤버의 행은
--                    금액만 새로 매기고 paid/paid_at 은 보존, 빠진 멤버의 행은 삭제, 새 멤버의 행은
--                    미납으로 추가한다.
--
-- created_at 는 BUILD_PLAN 3장 SettlementShare 모델에는 없으나 다른 모든 테이블과 같이 BaseTimeEntity 로
--            자동 관리한다(Phase 5·6 과 동일 처리). settlement_shares 는 settlements 에 종속되므로
--            ON DELETE CASCADE 로 묶는다.

CREATE TABLE settlements (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT      NOT NULL REFERENCES reservations(id),
    total_amount   INT         NOT NULL,
    split_type     VARCHAR(20) NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL,

    CONSTRAINT ck_settlements_split_type CHECK (split_type IN ('EQUAL', 'ATTENDEES_ONLY')),
    CONSTRAINT ck_settlements_total_amount CHECK (total_amount > 0),
    CONSTRAINT ux_settlements_reservation UNIQUE (reservation_id)
);

CREATE TABLE settlement_shares (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id BIGINT      NOT NULL REFERENCES settlements(id) ON DELETE CASCADE,
    user_id       BIGINT      NOT NULL REFERENCES users(id),
    amount        INT         NOT NULL,
    paid          BOOLEAN     NOT NULL DEFAULT FALSE,
    paid_at       TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL,

    CONSTRAINT ck_settlement_shares_amount CHECK (amount >= 0),
    CONSTRAINT ux_settlement_shares_member UNIQUE (settlement_id, user_id)
);

-- 정산 현황 조회: 정산별 몫 전부.
CREATE INDEX ix_settlement_shares_settlement ON settlement_shares (settlement_id);

COMMENT ON COLUMN settlements.total_amount IS '정산 총액(원). 0보다 크다. 몫 합계는 항상 이 값과 일치한다.';
COMMENT ON COLUMN settlements.split_type IS
    'EQUAL=현재 활성 멤버 전원 균등, ATTENDEES_ONLY=참석(ATTENDING) 멤버만 균등.';
COMMENT ON COLUMN settlement_shares.amount IS
    '이 멤버가 낼 몫(원). 나누어떨어지지 않는 나머지는 밴드장 먼저(없으면 최고참) 앞에서부터 1원씩 더한다.';
COMMENT ON COLUMN settlement_shares.paid IS '본인이 직접 체크하는 납부 완료 여부(셀프 리포트). 다른 멤버는 바꿀 수 없다.';
COMMENT ON COLUMN settlement_shares.paid_at IS 'paid 를 true 로 바꾼 시각. 체크를 취소하면 NULL 로 되돌린다.';
