-- Phase 8 게시판·미디어 업로드·신고·차단
--
-- board_posts  밴드 내부 게시판(합주 사진·영상 공유). 밴드 멤버만 읽고 쓴다. 삭제는 deleted_at 을 찍는
--              소프트 삭제다 — 이미 접수된 신고(reports.target_id)가 삭제 후에도 대상을 가리킬 수 있어야
--              하고, 첨부의 정리(EXPIRED 전환·R2 객체 삭제)를 별도 흐름으로 처리하기 때문이다.
--              도메인 모델(BUILD_PLAN 3장 BoardPost)에 updated_at 이 없으므로 수정 이력은 남기지 않는다.
--
-- media_attachments  사진·영상 첨부. 파일 바이트는 이 DB 도, 애플리케이션 서버도 지나지 않는다 —
--              클라이언트가 Cloudflare R2 로 presigned PUT 으로 직접 올리고, 서버는 storage_key 와
--              메타데이터만 갖는다(CLAUDE.md "백엔드를 경유하는 파일 스트림을 만들지 않는다").
--              status 흐름: PENDING(URL 발급 시 선생성) → READY(R2 HEAD 로 실제 크기·형식 확인) →
--              EXPIRED(보관기한 만료 또는 게시글 삭제로 R2 객체가 더 이상 없음).
--              클라이언트가 신고한 크기(size_bytes)와 실제 업로드 크기가 다르면 READY 로 가지 못하고
--              행과 R2 객체를 함께 지운다. expires_at 은 무료 플랜 기준 업로드일 + 30일이며,
--              프리미엄(Phase 10)은 NULL 이다. created_at 은 도메인 모델에는 없으나 다른 테이블과 같이
--              BaseTimeEntity 로 자동 관리한다(V7 settlement_shares 와 동일). 콜백이 오지 않은 PENDING
--              행을 나이순으로 청소하는 배치(Phase 9)의 정렬 키이기도 하다.
--
-- reports      게시글/미디어/사용자 신고 접수. target_id 는 세 테이블 중 하나를 가리키는 다형 참조라
--              외래키를 걸 수 없다 — target_type CHECK 와 인덱스로만 다룬다(V4 reservations.recurring_rule_id
--              와 같은 사유). 같은 대상에 대한 미처리(OPEN) 신고는 신고자당 하나로 부분 유니크 인덱스가
--              막는다(신고 스팸 방지). 처리(RESOLVED)용 운영 API 는 BUILD_PLAN Phase 8 범위 밖이라
--              status 컬럼만 두고 전이 API 는 만들지 않는다.
--
-- user_blocks  전역(밴드 무관) 사용자 차단. 게시판 목록·상세는 "내가 차단했거나 나를 차단한" 사용자의
--              글을 양방향으로 제외한다 — 단방향이면 차단 사실이 상대에게 역으로 드러난다.

CREATE TABLE board_posts (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    band_id    BIGINT        NOT NULL REFERENCES bands(id),
    author_id  BIGINT        NOT NULL REFERENCES users(id),
    title      VARCHAR(100)  NOT NULL,
    content    VARCHAR(4000) NOT NULL,
    created_at TIMESTAMPTZ   NOT NULL,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT ck_board_posts_title   CHECK (length(btrim(title)) > 0),
    CONSTRAINT ck_board_posts_content CHECK (length(btrim(content)) > 0)
);

-- 커서 페이징(band_id, created_at DESC, id DESC)을 그대로 태운다. 삭제된 글은 인덱스에서 뺀다.
CREATE INDEX ix_board_posts_band_created ON board_posts (band_id, created_at DESC, id DESC)
    WHERE deleted_at IS NULL;
-- 차단 필터가 author_id 로 좁힐 때, 그리고 사용자 탈퇴 시 역참조.
CREATE INDEX ix_board_posts_author ON board_posts (author_id);

CREATE TABLE media_attachments (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_post_id BIGINT       NOT NULL REFERENCES board_posts(id),
    storage_key   VARCHAR(200) NOT NULL,
    type          VARCHAR(20)  NOT NULL,
    status        VARCHAR(20)  NOT NULL,
    content_type  VARCHAR(100) NOT NULL,
    size_bytes    BIGINT       NOT NULL,
    uploaded_at   TIMESTAMPTZ,
    expires_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL,

    CONSTRAINT ck_media_attachments_type   CHECK (type IN ('IMAGE', 'VIDEO')),
    CONSTRAINT ck_media_attachments_status CHECK (status IN ('PENDING', 'READY', 'EXPIRED')),
    -- 영상 50MB(= 52428800 바이트)가 전체 상한. 이미지 10MB 는 형식별 규칙이라 애플리케이션(MediaPolicy)이 맡는다.
    CONSTRAINT ck_media_attachments_size   CHECK (size_bytes > 0 AND size_bytes <= 52428800),
    CONSTRAINT ck_media_attachments_ready  CHECK (status <> 'READY' OR uploaded_at IS NOT NULL),
    CONSTRAINT ux_media_attachments_key    UNIQUE (storage_key)
);

CREATE INDEX ix_media_attachments_post ON media_attachments (board_post_id);
-- 보관기한 만료 배치(Phase 9)용: 기한이 지난 READY 미디어를 R2 에서 지우고 EXPIRED 로 돌린다.
CREATE INDEX ix_media_attachments_expires ON media_attachments (expires_at)
    WHERE status = 'READY' AND expires_at IS NOT NULL;
-- 콜백이 오지 않은 고아 PENDING 청소 배치(Phase 9)용.
CREATE INDEX ix_media_attachments_pending ON media_attachments (created_at)
    WHERE status = 'PENDING';

CREATE TABLE reports (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(20)  NOT NULL,
    target_id   BIGINT       NOT NULL,
    reporter_id BIGINT       NOT NULL REFERENCES users(id),
    reason      VARCHAR(500) NOT NULL,
    status      VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL,

    CONSTRAINT ck_reports_target_type CHECK (target_type IN ('POST', 'MEDIA', 'USER')),
    CONSTRAINT ck_reports_status      CHECK (status IN ('OPEN', 'RESOLVED')),
    CONSTRAINT ck_reports_reason      CHECK (length(btrim(reason)) > 0)
);

-- 같은 대상에 대한 미처리 신고는 신고자당 하나. 처리(RESOLVED)된 뒤에는 다시 신고할 수 있다.
CREATE UNIQUE INDEX ux_reports_open_target ON reports (reporter_id, target_type, target_id)
    WHERE status = 'OPEN';
-- 운영자 처리 큐(오래된 미처리부터).
CREATE INDEX ix_reports_open_created ON reports (created_at) WHERE status = 'OPEN';

CREATE TABLE user_blocks (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_id      BIGINT      NOT NULL REFERENCES users(id),
    blocked_user_id BIGINT      NOT NULL REFERENCES users(id),
    created_at      TIMESTAMPTZ NOT NULL,

    CONSTRAINT ck_user_blocks_not_self CHECK (blocker_id <> blocked_user_id),
    CONSTRAINT ux_user_blocks_pair     UNIQUE (blocker_id, blocked_user_id)
);

-- "나를 차단한 사람" 역방향 조회(양방향 필터).
CREATE INDEX ix_user_blocks_blocked ON user_blocks (blocked_user_id);

COMMENT ON COLUMN board_posts.deleted_at IS
    '소프트 삭제 시각. 이미 접수된 신고가 대상을 계속 가리킬 수 있도록 행은 남긴다.';
COMMENT ON COLUMN media_attachments.storage_key IS
    'R2 객체 키. bands/{bandId}/posts/{postId}/{UUID} 형식이며 사용자 입력 파일명을 쓰지 않는다(경로 탈출·열거 방지).';
COMMENT ON COLUMN media_attachments.size_bytes IS
    '클라이언트가 신고한 바이트 수. 업로드 완료 콜백에서 R2 HEAD 로 실제 크기와 대조하며, 다르면 거부하고 객체와 행을 지운다.';
COMMENT ON COLUMN media_attachments.status IS
    'PENDING=URL 발급됨(아직 미확인), READY=HEAD 검증 통과, EXPIRED=보관기한 만료 또는 게시글 삭제로 객체 없음.';
COMMENT ON COLUMN media_attachments.expires_at IS
    '무료 플랜 보관기한(업로드일 + 30일). 프리미엄(Phase 10)은 NULL.';
COMMENT ON COLUMN reports.target_id IS
    'target_type 에 따라 board_posts/media_attachments/users 중 하나의 id. 다형 참조라 외래키를 걸 수 없다(V4 recurring_rule_id 와 같은 사유).';
COMMENT ON COLUMN user_blocks.blocked_user_id IS
    '차단 대상. 게시판 목록·상세에서 양방향(차단했거나 차단당했거나)으로 글이 제외된다. 밴드와 무관한 전역 차단이다.';
