-- Phase 9 알림 · 배치잡
--
-- notification_settings  사용자별 푸시 on/off 와 리마인더 시점(복수). user_id 가 PK 이자 users(id) FK
--              (도메인 모델 BUILD_PLAN 3장: NotificationSetting { userId, pushEnabled, reminderOffsets[] }).
--              reminder_offsets 는 "일정 시작 N분 전"의 분 단위 정수 배열이다. 별도 테이블 대신 integer[]
--              한 컬럼으로 둔다 — 사용자당 한 행이라 조회·수정이 단순하다. created_at 은 도메인 모델에
--              없으나 다른 테이블과 같이 BaseTimeEntity 로 자동 관리한다(V7·V8 선례).
--
-- device_tokens  FCM 디바이스 토큰. 같은 기기 토큰이 계정 전환으로 다른 사용자에게 붙을 수 있어
--              token 을 전역 유니크로 두고 재등록 시 소유자를 갱신한다(upsert). created_at 은 다른
--              테이블과의 정합을 위해 추가한다(도메인 모델은 updated_at 만 명시).
--
-- notification_dispatches  발송 이력 = 멱등 키. 리마인더 배치가 서버 재시작·재실행에도 같은 알림을
--              두 번 보내지 않도록 (user_id, type, target_id, variant) 유니크로 막는다. variant 는
--              리마인더의 offset(분)이고 그 외 트리거는 0 이다. 오래된 행은 배치가 주기적으로 지운다.

CREATE TABLE notification_settings (
    user_id          BIGINT      PRIMARY KEY REFERENCES users(id),
    push_enabled     BOOLEAN     NOT NULL DEFAULT TRUE,
    reminder_offsets INTEGER[]   NOT NULL DEFAULT '{60}',
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,

    CONSTRAINT ck_notification_settings_offsets
        CHECK (array_length(reminder_offsets, 1) IS NULL OR array_length(reminder_offsets, 1) <= 20)
);

CREATE TABLE device_tokens (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users(id),
    token      VARCHAR(255) NOT NULL,
    platform   VARCHAR(10)  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,

    CONSTRAINT ux_device_tokens_token    UNIQUE (token),
    CONSTRAINT ck_device_tokens_platform CHECK (platform IN ('IOS', 'ANDROID', 'WEB'))
);

CREATE INDEX ix_device_tokens_user ON device_tokens (user_id);

CREATE TABLE notification_dispatches (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    type       VARCHAR(40) NOT NULL,
    target_id  BIGINT      NOT NULL,
    variant    INTEGER     NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT ux_notification_dispatches UNIQUE (user_id, type, target_id, variant)
);

-- 보관기한 지난 발송 이력을 나이순으로 지우는 정리 쿼리의 인덱스.
CREATE INDEX ix_notification_dispatches_created ON notification_dispatches (created_at);

-- 리마인더·독촉 배치가 "곧 시작하는 확정 일정"을 훑는 경로. 쿼리 조건(status = 'CONFIRMED')과
-- 부분 인덱스를 일치시킨다.
CREATE INDEX ix_reservations_upcoming ON reservations (start_at) WHERE status = 'CONFIRMED';

COMMENT ON COLUMN notification_settings.reminder_offsets IS
    '일정 시작 N분 전 리마인더 시점의 분 단위 정수 배열. 예: {10,60} = 10분 전과 60분 전 두 번.';
COMMENT ON COLUMN device_tokens.token IS
    'FCM 등록 토큰. 전역 유니크 — 기기가 계정 전환되면 재등록 시 user_id 만 갱신한다.';
COMMENT ON COLUMN notification_dispatches.variant IS
    '같은 (user,type,target) 안에서 발송을 구분하는 값. 리마인더는 offset(분), 그 외 트리거는 0.';
